### ISSUE TITLE
Docker does not run on Ubuntu with localhost:8080

### ISSUE THREAD

**Issue by k00ni** [Dockerizing/NodeJS-NPM-ECMA6-Stack#1]
In the latest version the docker container does not publish under Ubuntu 14.04 a valid site under localhost:8080.

**Comment by GeorgesAlkhouri** [comment]
Fixed: 12f6f41cd035a84b41f6212e83c0c24a0d479ca8

I'll add a detailed README in a few weeks. 
@k00ni feel free to try it and close the issue :)

**Comment by k00ni** [comment]
:+1:
